name: BosMon RTL-SDR
version: v0.1.1
slug: bosmon-rtlsdr
description: RTL-SDR Pocsag receiver
url: https://github.com/timniklas/addon-bosmon-rtlsdr
image: ghcr.io/timniklas/addon-bosmon-rtlsdr
startup: services
arch:
- amd64
options:
  frequency: 439.9875M
  gain: 100
schema:
  device: "device"
  frequency: "match([0-9_]+[.][0-9_]+M)"
  gain: "int"
  bosmon_url: "url"
  bosmon_username: "match([a-zA-Z0-9_]+)"
  bosmon_password: "password"
  bosmon_endpoint: "match([a-zA-Z0-9_]+)"
